# Generated by Django 4.0.3 on 2022-08-22 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_project_created_at_alter_project_git_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='stack',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.stack'),
        ),
        migrations.AddField(
            model_name='stack',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
