# Generated by Django 4.1 on 2022-08-27 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_project_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to=''),
        ),
    ]
